import httpx
from typing import List, Dict

class SpotifyService:
    def __init__(self, access_token: str):
        self.access_token = access_token
        self.headers = {"Authorization": f"Bearer {self.access_token}"}
        
    async def get_current_user_profile(self) -> dict:
        """
        Gets the current user's profile information.
        """
        async with httpx.AsyncClient() as client:
            response = await client.get(
                "https://api.spotify.com/v1/me",
                headers=self.headers
            )
            response.raise_for_status()
            return response.json()

    async def get_artist_genres(self, artist_ids: List[str]) -> Dict[str, List[str]]:
        """
        Given a list of artist IDs, returns a dictionary mapping artist_id -> list of genres.
        Spotify allows up to 50 artists per request.
        """
        genres_map = {}
        
        # We need to chunk the artist_ids into batches of 50
        chunk_size = 50
        artist_id_chunks = [artist_ids[i:i + chunk_size] for i in range(0, len(artist_ids), chunk_size)]
        
        async with httpx.AsyncClient() as client:
            for chunk in artist_id_chunks:
                ids_string = ",".join(chunk)
                
                response = await client.get(
                    f"https://api.spotify.com/v1/artists?ids={ids_string}",
                    headers=self.headers
                )
                
                if response.status_code == 200:
                    data = response.json()
                    for artist in data.get("artists", []):
                        if artist and "id" in artist:
                            genres_map[artist["id"]] = artist.get("genres", [])
                            
        return genres_map
        
    async def get_track_artists(self, track_ids: List[str]) -> Dict[str, str]:
        """
        Given track IDs, finds the primary artist ID for each track.
        Useful for when KNN engine returns track IDs, but we need artist IDs to check genres.
        """
        # Similar logic to get_artist_genres, utilizing Spotify's /tracks endpoint 
        # Up to 50 tracks per request.
        track_to_artist = {}
        chunk_size = 50
        track_id_chunks = [track_ids[i:i + chunk_size] for i in range(0, len(track_ids), chunk_size)]
        
        async with httpx.AsyncClient() as client:
            for chunk in track_id_chunks:
                ids_string = ",".join(chunk)
                response = await client.get(
                    f"https://api.spotify.com/v1/tracks?ids={ids_string}",
                    headers=self.headers
                )
                
                if response.status_code == 200:
                    data = response.json()
                    for track in data.get("tracks", []):
                        if track and track.get("artists"):
                            # Grab the primary (first) artist
                            track_to_artist[track["id"]] = track["artists"][0]["id"]
                            
        return track_to_artist

    async def create_playlist(self, spotify_user_id: str, name: str) -> str:
        """
        Creates a new playlist on the user's Spotify account.
        Returns the new playlist's ID.
        """
        async with httpx.AsyncClient() as client:
            response = await client.post(
                f"https://api.spotify.com/v1/users/{spotify_user_id}/playlists",
                headers=self.headers,
                json={
                    "name": name,
                    "description": "Generated by Tangent",
                    "public": False
                }
            )
            response.raise_for_status()
            data = response.json()
            return data["id"]

    async def add_items_to_playlist(self, playlist_id: str, track_ids: List[str]):
        """
        Adds tracks to a Spotify playlist. 
        Note: Spotify expects URIs, so we prepend 'spotify:track:' to the track_ids.
        Max 100 tracks per request.
        """
        uris = [f"spotify:track:{tid}" for tid in track_ids]
        
        chunk_size = 100
        uri_chunks = [uris[i:i + chunk_size] for i in range(0, len(uris), chunk_size)]
        
        async with httpx.AsyncClient() as client:
            for chunk in uri_chunks:
                response = await client.post(
                    f"https://api.spotify.com/v1/playlists/{playlist_id}/tracks",
                    headers=self.headers,
                    json={"uris": chunk}
                )
                response.raise_for_status()
