CREATE TABLE IF NOT EXISTS "playlist_songs" (
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "playlist_id" uuid NOT NULL,
    "song_id" text NOT NULL,
    "distance_score" float NOT NULL,
    CONSTRAINT "uniq_playlist_song" UNIQUE ("playlist_id", "song_id")
);